name: smart_sale_boss
description: "Smart sale boos project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_info_plus: ^11.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  http_interceptor: ^2.0.0
  intl: ^0.19.0
  logger: ^2.4.0
  mask_text_input_formatter: ^2.9.0
  package_info_plus: ^8.0.3
  shimmer: ^3.0.0

dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Italic-VariableFont.ttf
        - asset: assets/fonts/inter/Inter-VariableFont.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
